### PR TITLE
Add support for orthographic camera

### LINKED ISSUE #4: Atmosphere: Add support for "OrthographicCamera"
Currently when rendering with an orthographic camera the atmosphere doesn't look right. It would be great to support an orthographic camera, as well. Are there any inherent limitations with the current approach that would prevent it from working?

You can recreate this by adding the `orthographic` property to the `<Canvas>` component.

image

_edit: It looks like this is probably (in part) caused by the assumption that the camera position is the view ray origin in the [fragment shaders](https://github.com/takram-design-engineering/three-geospatial/blob/2f1dd0f30d1bd9247d04a6c0d9fd9ee361e82ff5/packages/atmosphere/src/shaders/sky.vert#L13-L17). Instead we could probably using the inverse projection matrix to determine the ray origin at the near clip plane. Let me know what you think!_

### PR DESCRIPTION
**Pull request by gkjohnson**
Fix #4 

Adds support for atmospheric perspective rendering with an orthographic camera. It's possible to calculate the camera ray for each camera type with the same logic but in order to avoid floating point error accumulation where possible the perspective ray generation is handled differently from orthographic.

**Orthographic screenshots**

image image

**Some notes**
- The stars shader hasn't been adjusted since it won't make sense to render the background stars with an orthographic camera, though this can result in some artifacts when they _are_ enabled.
- The "getCameraRay" function has been copied between two shaders since it relies on local uniforms but I'm happy to hear how you'd prefer to adjust things.
- Due to the way GlobeControls (and orthographic cameras) work you will see the "thickness" of atmospheric accumulation change as you rotate the camera. This is because the orthographic camera origin and near plane meaning there's technically more "atmosphere" in front of the camera but the view otherwise will look the same. This is something I'll have to think about further.

### CODE REVIEW

**Comment by shotamatsuda** [comment]
Wow, I wasn’t expecting this. I will take a closer look later today!

**Comment by shotamatsuda** [comment]
Looks good to me on your changes. Thanks so much for working on this! Maybe I will disable stars when used with an orthographic camera later. I’m fine with the duplicated getCameraRay for now. I’ll separate it when I need it elsewhere.

> This is because the orthographic camera origin and near plane meaning there’s technically more “atmosphere” in front of the camera but the view otherwise will look the same.

As I’m not familiar with the orthographic camera, I don’t fully understand this. I see that the view position is determined by the unprojected near point. Is it be caused by the near/far changing in GlobeControls? 

What I’m wondering is, when logarithmic depth is enabled, the sun irradiance in deferred lighting seems off. You can see this by using an orthographic camera in the Atmosphere/Basic story. Does it make sense to use logarithmic depth with orthographic projection?

https://github.com/user-attachments/assets/5cd4ea2d-7e11-425f-b011-95ebf0816ebc

↑ "deferred" and "forward" differ significantly (due to sun irradiance), and the sun irradiance is visible even from below the horizon in "deferred".

**Comment by gkjohnson** [comment]
> As I’m not familiar with the orthographic camera, I don’t fully understand this. I see that the view position is determined by the unprojected near point. **Is it caused by the near/far changing in GlobeControls?**

I believe so, yes - GlobeControls shifts the "near" plane and ortho camera position to make sure that all tile geometry is in view and not clipped as the navigate. Because of the nature of an orthographic projection you can typically move the near plan backwards which will result in no change to the rendered image. However because the near plane is defining the ray origin and the distance to a surface determines the "thickness" of the atmosphere rendered it results in this look of changing atmosphere.

> What I’m wondering is, when logarithmic depth is enabled, the sun irradiance in deferred lighting seems off. You can see this by using an orthographic camera in the Atmosphere/Basic story. Does it make sense to use logarithmic depth with orthographic projection?

I'm not using logarithmic depth buffer but checking it now I'm seeing that the atmosphere doesn't work well in the photorealistic tiles example when rendering with an ortho camera. I'm not sure why logarithmic buffer _wouldn't_ work with it beyond some kind of precision quirk somewhere. I don't think I have time to dig into the details of logarithmic depth rendering but maybe we can make a separate issue for this and I can revisit it later if it becomes an issue?

image

Also I can add a toggle to the demos for an orthographic camera if you'd like.

**Comment by shotamatsuda** [comment]
Thank you for your explanation.

I don’t think the cause is within the atmospheric scattering itself, so maybe I made a mistake somewhere. Agreed, there’s nothing stopping us from merging this feature. I’ll open another issue and revisit it later.

A demo for this would be great. Please create another PR for it whenever you have time. Unorganized code is fine. I’ll work on it as needed to better understand what’s going on around the transition.

**Pull request merged**
